spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    connection-timeout: 10000
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: felipeortegasouza@gmail.com
    password: zqgpjnhdugifhzwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  destinatario: Miguelcserpa@gmail.com
  assunto: "Notificação CR Metais"

broker:
  exchange:
    name: example.fanout.exchange
  queue:
    name: example.queue

server:
  port: 8080